  transform:
    name: business-transformer-${opt:stage, self:provider.stage}
    handler: src/handlers/${self:provider.name}/business-transformer-handler.handle
    timeout: 300
    package:
      include:
        - src/handlers/${self:provider.name}/business-transformer-handler.js
        - node_modules/business-transformer/**
    events:
      - http:
          path: transform
          method: post
          cors: true
